FROM node:20-bullseye-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-bullseye-slim
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY --from=builder /app/dist ./dist
COPY prisma/ ./prisma/
RUN npx prisma generate
RUN npx prisma migrate deploy
EXPOSE 3001
CMD ["node", "dist/src/index.js"]
